# Set the device
device: cuda
# Set a fixed random seed for reproducibility, or null
manual_seed: null
# model configuration
model:
  # model class
  name: GatNet_SF
  # number of input channels to the model
  in_channels: 99
  # number of output classes
  out_channels: 8
  # number of nodes
  num_nodes: 100
# trainer configuration
trainer:
  # path to the checkpoint directory
  checkpoint_dir: /home/sherry/Dropbox/PhD/gcn_for_pnc/checkpoints
  # path to latest checkpoint or null; if provided the training will be resumed
  resume: null
  # how many iterations between validations, null if validate every epoch
  validate_after_iters: null
  # how many iterations between tensorboard logging
  log_after_iters: null
  # how many iterations evaluated in validations, set null for evaluating whole val set
  validate_iters: null
  # max number of epochs
  epochs: 400
  # max number of iterations, set null for finishing all epochs
  iters: null
  # model with higher eval score is considered better
  eval_score_higher_is_better: False
# optimizer configuration
optimizer:
  # initial learning rate
  learning_rate: 0.001
  # weight decay
  weight_decay: 0.0001
# loss function configuration
loss:
  # loss function to be used during training
  name: MSEClassLoss
  #class_counts: /home/sherry/Dropbox/PhD/Results/pnc_strucfunc_exp01/processed/train_exp01_ScanAgeYears_hist.npy
  ratio: 2
  base: 8
# evaluation metric configuration
eval_metric:
  # evaluation metric to be used during training
  name: ClassRMSE
  ratio: 2
  base: 8
lr_scheduler:
  name: MultiStepLR
  milestones: [100]
  gamma: 0.1
# data loaders configuration
loaders:
  # name of the dataset
  name: PNCEnrichedSet
  # class name of the dataloader
  loader_name: DataLoader
  # root path to save the created dataset
  root: /home/sherry/Dropbox/PhD/Results/pnc_strucfunc_exp01
  # paths to the training list file
  train_list: /home/sherry/Dropbox/PhD/Results/pnc_strucfunc_exp01/cv_list/train_list_fold0.txt
  # output filename for training dataset
  output_train: train_exp01.pkl
  # train val split ratio from train_list
  train_val_ratio: [3, 1]
  # paths to the test list file
  test_list: /home/sherry/Dropbox/PhD/Results/pnc_strucfunc_exp01/cv_list/test_list_fold0.txt
  # output filename for test dataset
  output_test: test_exp01.pkl
  # path to origianl data folder
  path_data: /home/sherry/Dropbox/PhD/Data/PNC_Enriched/PNC_Connectomes
  # path to origianl label file
  path_label: /home/sherry/Dropbox/PhD/Data/PNC_Enriched/PNC_Connectomes_GO1_n968_LTN_dtiQApass_t1QApass_fsQApass.xlsx
  # prediction target name
  target_name: ScanAgeYears
  # index of features to keep, or features with a certain number of node
  feature_mask: 100
  # batch size in training process
  batch_size: 64